{
    "_Type": "Action.Type.ODataService.DraftEnabled.Edit",
    "Target": {
        "Service": "/risksmobikle/Services/RiskManagement01Service.service",
        "EntitySet": "Mitigations",
        "ReadLink": "{@odata.readLink}"
    },
    "ShowActivityIndicator": true,
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": {
        "Name": "/risksmobikle/Actions/UpdateEntitySuccessMessage.action",
        "Properties": {
            "Message": "Draft Edit"
        }
    },
    "OnFailure": "/risksmobikle/Actions/UpdateEntityFailureMessage.action"
}